#!/bin/sh
rm -rf /usr/share/enigma2/OPD-Blue-Line
rm -rf /usr/lib/enigma2/python/Components/Converter/OPD*
rm -rf /usr/lib/enigma2/python/Components/Renderer/OPD*
echo "                                                          "
echo " ....Skin removed! You should restart GUI now!                 "
echo "    
