#!/bin/sh
rm -rf /usr/share/enigma2/OPD-Blue-Line
rm -rf /usr/lib/enigma2/python/Components/Converter/OPD*
rm -rf /usr/lib/enigma2/python/Components/Renderer/OPD*
echo "                                                                     "
echo "OPD-Blue-Line skin was successfully removed from your receiver       "
echo "                                                                     "
echo "The GUI of your receiver is now rebooting....                        "
sleep 5
init 4 && sleep 5 && init 3
