#!/bin/sh
    rm -rf /usr/share/enigma2/OPD-Blue-Line
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDAnalogClock
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDBlinkingClock
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDcaid
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDCPUInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDCryptInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDEmuInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDExtraInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDFrontendInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDPrimeTime
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDReceiverInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDRefString
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDServiceEndTime
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDServiceInfo
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDServiceName
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDServiceNameEventNobile
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDTemp
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDValueBitTest
    rm -rf /usr/lib/enigma2/python/Components/Converter/OPDValueRange
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDEmptyEpg
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDNextEvents
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDRunningText
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDSingleEpgListFull
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDSYSTemp
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDVolume
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDWatches
    rm -rf /usr/lib/enigma2/python/Components/Renderer/OPDXPicon
echo "                                                                     "
echo "OPD-Blue-Line skin was successfully removed from your receiver       "
echo "                                                                     "
echo "The GUI of your receiver is now rebooting....                        "
sleep 5
init 4 && sleep 5 && init 3
