#!/bin/sh
echo "                                                                   "
echo "OPD-Blue-Line skin is now being removed from your receiver         "
echo "                                                                   "
