name: Skins-for-openOPD

on:
  push:
    branches: [ master,  python3 ]
  pull_request:
    branches: [ master,  python3 ]

jobs:
  build:
    name: Build oe-alliance plugins
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get install automake
          sudo apt-get install build-essential
          sudo apt-get install gettext

      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build, python 2.7
        run: |
          python -m compileall .

      - uses: actions/checkout@v2
        with:
          ref: 'python3'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build, python 3.8
        run: |
          python -m compileall .

      - uses: actions/checkout@v2
        with:
          ref: 'python3'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build, python 3.9
        run: |
          sudo apt-get install python3.9-python3
          python -m compileall .
